version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /opt/flask-postgres-boilerplate:/counter_app
    links:
      - db:postgres
    container_name: counterapppostgres_web_1
    depends_on:
      - db
    environment:
        PORT: 5000
        SECRET_KEY: 'you-will-never-guess'
        DB_USERNAME: counter_user
        DB_PASSWORD: counter_password
        DB_HOST: postgres
        DATABASE_NAME: counter
  db:
    image: postgres:9.6
    restart: always
    container_name: counterapppostgres_db_1
    environment:
        POSTGRES_USER: counter_user
        POSTGRES_PASSWORD: counter_password
        POSTGRES_DB: counter
